name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  start-app:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Start Backend
      run: npm run start:server
    - name: Start Frontend
      run: npm run start:frontend

  eslint:
    needs: start-app
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run ESLint
      run: npm run lint

  cypress:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test
