name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint

  api-tests:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Run API tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:server
          command: npm run test:api

  gui-tests:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run GUI tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:frontend
          command: npm run test:gui
